# Generated by Django 5.0.1 on 2025-10-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aiactionlog',
            new_name='ai_actions__action__00ff52_idx',
            old_name='ai_action_a_action__800ee1_idx',
        ),
        migrations.RenameIndex(
            model_name='aiactionlog',
            new_name='ai_actions__status_69c4d2_idx',
            old_name='ai_action_a_status__e363a7_idx',
        ),
        migrations.RenameIndex(
            model_name='aiactionlog',
            new_name='ai_actions__created_327688_idx',
            old_name='ai_action_a_created_315050_idx',
        ),
        migrations.RenameIndex(
            model_name='aiservicetoken',
            new_name='ai_actions__user_id_cdc99e_idx',
            old_name='ai_action_u_user_i_7091f5_idx',
        ),
        migrations.RenameIndex(
            model_name='aiservicetoken',
            new_name='ai_actions__key_pre_eaf1d9_idx',
            old_name='ai_action_k_key_pre_3bfad0_idx',
        ),
    ]
