# Generated by Django 5.0.1 on 2025-10-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cra',
            name='selected_work_dates',
            field=models.JSONField(blank=True, default=list, help_text="All dates marked as worked in the calendar for this period (e.g., ['2025-10-01', '2025-10-05'])", verbose_name='Selected Work Dates'),
        ),
    ]
