# Generated by Django 5.0.1 on 2025-10-20 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='estimated_budget',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Estimated project budget', max_digits=12),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='todo', max_length=20)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, help_text='Estimated hours for this task', max_digits=8)),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, help_text='Actual hours spent on this task', max_digits=8)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Hourly rate for this task', max_digits=8)),
                ('order', models.IntegerField(default=0, help_text='Order of task in list')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'indexes': [models.Index(fields=['project', 'status'], name='projects_ta_project_cd2085_idx'), models.Index(fields=['order'], name='projects_ta_order_ecbe9d_idx')],
            },
        ),
    ]
