# Generated by Django 5.0.1 on 2025-10-22 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0001_initial'),
        ('projects', '0002_project_estimated_budget_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the task')),
                ('category', models.CharField(choices=[('development', 'Development'), ('design', 'Design'), ('testing', 'Testing'), ('deployment', 'Deployment'), ('consulting', 'Consulting'), ('documentation', 'Documentation'), ('maintenance', 'Maintenance'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=50)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Tags for categorization (array of strings)')),
                ('average_estimated_hours', models.DecimalField(decimal_places=2, default=0, help_text='Average estimated hours across all uses', max_digits=8)),
                ('min_hours', models.DecimalField(decimal_places=2, default=0, help_text='Minimum hours observed', max_digits=8)),
                ('max_hours', models.DecimalField(decimal_places=2, default=0, help_text='Maximum hours observed', max_digits=8)),
                ('average_actual_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Average actual hours from completed tasks', max_digits=8, null=True)),
                ('average_hourly_rate', models.DecimalField(decimal_places=2, default=0, help_text='Average hourly rate used', max_digits=8)),
                ('usage_count', models.IntegerField(default=0, help_text='Number of times this template has been used')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this template was used', null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=50.0, help_text='Confidence score 0-100 based on estimate accuracy', max_digits=5)),
                ('created_from', models.CharField(choices=[('manual', 'Manual Creation'), ('ai_import', 'AI Import'), ('task_conversion', 'Converted from Task')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count', '-last_used_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(help_text='Where this task came from (ai_import, manual, template)', max_length=50)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('variance_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Difference between estimated and actual as percentage', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_processing.importeddocument')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='projects.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_entries', to='projects.tasktemplate')),
            ],
            options={
                'verbose_name_plural': 'Task histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Task template this was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='projects.tasktemplate'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['template'], name='projects_ta_templat_c716ae_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['user', 'category'], name='projects_ta_user_id_6340df_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['user', 'is_active'], name='projects_ta_user_id_ea7d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['usage_count'], name='projects_ta_usage_c_4e92dd_idx'),
        ),
        migrations.AddIndex(
            model_name='tasktemplate',
            index=models.Index(fields=['last_used_at'], name='projects_ta_last_us_fa9a70_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tasktemplate',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['user', 'template'], name='projects_ta_user_id_f61a33_idx'),
        ),
        migrations.AddIndex(
            model_name='taskhistory',
            index=models.Index(fields=['created_at'], name='projects_ta_created_73ac7b_idx'),
        ),
    ]
