# Generated by Django 5.0.1 on 2025-10-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tasktemplate_taskhistory_task_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worked_days',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Days worked on this task (for CRA)', max_digits=8),
        ),
    ]
