# Generated by Django 5.0.1 on 2025-10-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_task_worked_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='worked_dates',
            field=models.JSONField(blank=True, default=list, help_text="Specific dates worked on this task for CRA (e.g., ['2025-10-01', '2025-10-05'])"),
        ),
    ]
