# Generated by Django 5.0.1 on 2025-11-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_task_worked_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktemplate',
            name='category',
            field=models.CharField(choices=[('development', 'Development'), ('automation', 'Automation'), ('ui_ux_design', 'UI/UX Design'), ('graphic_design', 'Graphic Design'), ('video_editing', 'Video Editing'), ('3d_modeling', '3D Modeling'), ('content_writing', 'Content Writing'), ('translation', 'Translation'), ('marketing', 'Marketing'), ('accounting', 'Accounting'), ('audio_production', 'Audio Production'), ('testing', 'Testing'), ('deployment', 'Deployment'), ('consulting', 'Consulting'), ('documentation', 'Documentation'), ('maintenance', 'Maintenance'), ('research', 'Research'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
