# Generated by Django 5.0.1 on 2025-10-20 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
        ('projects', '0002_project_estimated_budget_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='projects.project'),
        ),
    ]
