# Generated by Django 5.0.1 on 2025-10-21 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_email'),
        ('invoicing', '0002_estimate_project'),
        ('projects', '0002_project_estimated_budget_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Whether this estimate was generated with AI assistance'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='ai_metadata',
            field=models.JSONField(blank=True, default=dict, help_text='AI generation metadata (suggestions, confidence, historical context)'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='parent_estimate',
            field=models.ForeignKey(blank=True, help_text='Links to original estimate for revisions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='invoicing.estimate'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='security_margin_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated security margin amount', max_digits=12, verbose_name='Montant de la marge'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='security_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Security margin percentage (e.g., 10.00 for 10%)', max_digits=5, verbose_name='Marge de sécurité (%)'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='signature_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de signature'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='signature_data',
            field=models.JSONField(blank=True, default=dict, help_text='Signature metadata (IP, timestamp, certificate info, method)'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='signature_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de demande de signature'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='signature_status',
            field=models.CharField(choices=[('none', 'None'), ('requested', 'Requested'), ('signed', 'Signed'), ('declined', 'Declined')], default='none', max_length=20, verbose_name='Statut de signature'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='signed_pdf_file',
            field=models.FileField(blank=True, help_text='Signed version of the estimate PDF', null=True, upload_to='estimates/signed/%Y/%m/', verbose_name='PDF signé'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='subtotal_before_margin',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Subtotal before security margin is applied', max_digits=12),
        ),
        migrations.AddField(
            model_name='estimate',
            name='terms',
            field=models.TextField(blank=True, help_text='Terms and conditions for this specific estimate', verbose_name='Conditions générales'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='tjm_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='TJM rate used for this estimate (snapshot for historical tracking)', max_digits=8, null=True, verbose_name='TJM utilisé'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='total_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total number of days if using TJM-based pricing', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='version',
            field=models.IntegerField(default=1, help_text='Version number for tracking estimate revisions'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='items',
            field=models.JSONField(default=list, help_text='Line items: [{description, quantity, unit, rate, amount}]'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, help_text='Subtotal after margin (subtotal_before_margin + security_margin_amount)', max_digits=12),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['signature_status'], name='invoicing_e_signatu_2f8e82_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['version'], name='invoicing_e_version_000541_idx'),
        ),
    ]
