# Generated by Django 5.0.1 on 2025-10-21 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_estimate_ai_generated_estimate_ai_metadata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signer_name', models.CharField(max_length=255, verbose_name='Nom du signataire')),
                ('signer_email', models.EmailField(max_length=254, verbose_name='Email du signataire')),
                ('signer_company', models.CharField(blank=True, max_length=255, verbose_name='Société du signataire')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Token d'accès")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('signed', 'Signed'), ('expired', 'Expired'), ('declined', 'Declined')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('signed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de signature')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de première consultation')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('signature_method', models.CharField(blank=True, choices=[('draw', 'Drawn Signature'), ('upload', 'Uploaded Image'), ('type', 'Typed Name'), ('digital', 'Digital Certificate')], max_length=20, verbose_name='Méthode de signature')),
                ('signature_image', models.FileField(blank=True, null=True, upload_to='signatures/%Y/%m/', verbose_name='Image de signature')),
                ('signature_metadata', models.JSONField(blank=True, default=dict, help_text='Additional signature data (typed name, certificate info, etc.)', verbose_name='Métadonnées de signature')),
                ('decline_reason', models.TextField(blank=True, verbose_name='Raison du refus')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Email envoyé le')),
                ('email_opened_count', models.IntegerField(default=0, verbose_name="Nombre d'ouvertures email")),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='invoicing.estimate', verbose_name='Devis')),
            ],
            options={
                'verbose_name': 'Demande de signature',
                'verbose_name_plural': 'Demandes de signature',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='invoicing_s_token_a5d2a6_idx'), models.Index(fields=['status'], name='invoicing_s_status_508aec_idx'), models.Index(fields=['estimate'], name='invoicing_s_estimat_03c4f0_idx'), models.Index(fields=['expires_at'], name='invoicing_s_expires_c78d5e_idx')],
            },
        ),
    ]
