# Generated by Django 5.0.1 on 2025-10-22 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_signaturerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='credit_note_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation/credit note'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_credit_note',
            field=models.BooleanField(default=False, help_text="Is this a credit note (facture d'avoir)?"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, help_text='Original invoice if this is a credit note', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='invoicing.invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount already paid', max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date of (last) payment', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment method (bank_transfer, check, cash, credit_card, paypal, other)', max_length=50),
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_estimate',
            field=models.ForeignKey(blank=True, help_text='Source estimate if this invoice was converted from an estimate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_invoices', to='invoicing.estimate'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('converted', 'Converted to Invoice')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('credit_note', 'Credit Note')], default='draft', max_length=20),
        ),
    ]
