# Generated by Django 5.0.1 on 2025-10-22 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0005_invoice_credit_note_reason_invoice_is_credit_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='deposit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage of total for this deposit (e.g., 30.00 for 30%)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_deposit_invoice',
            field=models.BooleanField(default=False, help_text="Is this a deposit invoice (facture d'acompte)?"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='parent_invoice',
            field=models.ForeignKey(blank=True, help_text='Parent invoice if this is a deposit invoice', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deposit_invoices', to='invoicing.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('credit_note', 'Credit Note'), ('partially_invoiced', 'Partially Invoiced'), ('deposit', 'Deposit Invoice')], default='draft', max_length=20),
        ),
    ]
