# Generated by Django 5.0.1 on 2025-10-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_invoice_deposit_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_final_balance_invoice',
            field=models.BooleanField(default=False, help_text='Is this a final balance invoice (SOLDE) consolidating all deposits?'),
        ),
    ]
