# Generated by Django 5.0.1 on 2025-10-22 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_email'),
        ('invoicing', '0007_invoice_is_final_balance_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='draft_uuid',
            field=models.UUIDField(blank=True, db_index=True, help_text='Temporary UUID for drafts before finalization', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='estimate_number',
            field=models.CharField(blank=True, help_text='Final estimate number (DEVIS-YYYY-NNNN)', max_length=50, null=True, unique=True),
        ),
    ]
