# Generated by Django 5.0.1 on 2025-10-23 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cra', '__first__'),
        ('invoicing', '0008_estimate_draft_uuid_alter_estimate_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='source_cra',
            field=models.ForeignKey(blank=True, help_text='Source CRA if this invoice was generated from an activity report', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_invoices', to='cra.cra'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='security_margin_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculated security margin amount', max_digits=12, verbose_name='Margin amount'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='security_margin_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Security margin percentage (e.g., 10.00 for 10%)', max_digits=5, verbose_name='Security margin (%)'),
        ),
    ]
