# Generated by Django 5.0.1 on 2025-11-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_invoice_source_cra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='items',
            field=models.JSONField(default=list, help_text='Line items: [{description, quantity, unit, rate, amount}]'),
        ),
    ]
