# Generated by Django 5.0.1 on 2025-10-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importpreview',
            name='auto_approve_eligible',
            field=models.BooleanField(default=False, help_text='True if import meets criteria for automatic approval (>90% confidence, no conflicts)'),
        ),
        migrations.AddField(
            model_name='importpreview',
            name='clarification_completed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when user completed task clarification flow', null=True),
        ),
        migrations.AddField(
            model_name='importpreview',
            name='needs_clarification',
            field=models.BooleanField(default=False, help_text='True if any task has clarity score <80% and needs user clarification'),
        ),
        migrations.AddField(
            model_name='importpreview',
            name='overall_task_quality_score',
            field=models.IntegerField(default=100, help_text='Average task quality score across all tasks (0-100)'),
        ),
        migrations.AddField(
            model_name='importpreview',
            name='task_quality_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Per-task quality analysis results: {task_index: {score, clarity_level, issues, ...}}'),
        ),
        migrations.AlterField(
            model_name='importpreview',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('needs_clarification', 'Needs Clarification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
    ]
