# Generated by Django 5.0.1 on 2025-10-23 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0003_aimodelversion_aiextractionfeedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodelversion',
            name='fine_tuned_model',
            field=models.CharField(blank=True, help_text='Name of the fine-tuned model from OpenAI', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aimodelversion',
            name='training_error',
            field=models.TextField(blank=True, help_text='Error message if training failed', null=True),
        ),
    ]
