# Generated by Django 5.0.1 on 2025-11-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_processing', '0004_aimodelversion_fine_tuned_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='importeddocument',
            name='clarification_history',
            field=models.JSONField(blank=True, default=dict, help_text='Stores user-refined task data to preserve across reparses. Structure: {task_identifier: {refined_data, timestamp, version}}'),
        ),
        migrations.AddField(
            model_name='importeddocument',
            name='preserve_clarifications_on_reparse',
            field=models.BooleanField(default=True, help_text='If True, merge previous clarifications when reparsing; if False, start fresh'),
        ),
    ]
