# Generated by Django 5.0.1 on 2025-10-21 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, help_text='Company or freelance business name', max_length=255)),
                ('company_logo', models.ImageField(blank=True, help_text='Company logo for PDFs', null=True, upload_to='company_logos/')),
                ('address', models.TextField(blank=True, help_text='Street address')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(default='France', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Business email (optional, defaults to user email)', max_length=254)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='TVA Intracommunautaire')),
                ('siret_siren', models.CharField(blank=True, max_length=50, verbose_name='SIRET/SIREN')),
                ('iban', models.CharField(blank=True, max_length=34, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=11, verbose_name='BIC/SWIFT')),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('tjm_default', models.DecimalField(decimal_places=2, default=500.0, help_text='Taux Journalier Moyen (daily rate) in default currency', max_digits=8, verbose_name='TJM par défaut')),
                ('hourly_rate_default', models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated from TJM or set manually', max_digits=8, verbose_name='Taux horaire par défaut')),
                ('tjm_hours_per_day', models.IntegerField(default=7, help_text='Number of billable hours per day (for TJM to hourly conversion)', verbose_name='Heures par jour')),
                ('tjm_rates', models.JSONField(blank=True, default=dict, help_text="Multiple TJM rates by service type: {'development': 500, 'consulting': 650}", verbose_name='TJM par type de prestation')),
                ('default_security_margin', models.DecimalField(decimal_places=2, default=10.0, help_text='Default security margin percentage for estimates (e.g., 10.00 for 10%)', max_digits=5, verbose_name='Marge de sécurité par défaut (%)')),
                ('show_security_margin_on_pdf', models.BooleanField(default=False, help_text='If True, security margin is visible on client PDFs as a separate line item', verbose_name='Afficher la marge sur les PDF')),
                ('payment_terms_days', models.IntegerField(default=30, help_text='Default payment terms in days (30, 45, 60)', verbose_name='Délai de paiement (jours)')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=20.0, help_text='Default VAT/tax rate (e.g., 20.00 for 20%)', max_digits=5, verbose_name='Taux de TVA par défaut (%)')),
                ('currency', models.CharField(choices=[('EUR', 'Euro (€)'), ('USD', 'US Dollar ($)'), ('GBP', 'British Pound (£)'), ('CHF', 'Swiss Franc (CHF)')], default='EUR', max_length=3)),
                ('pdf_footer_text', models.TextField(blank=True, help_text='Custom footer text for invoices and estimates', verbose_name='Texte de pied de page PDF')),
                ('pdf_primary_color', models.CharField(default='#3B82F6', help_text='Hex color code for PDF branding (e.g., #3B82F6)', max_length=7, verbose_name='Couleur principale PDF')),
                ('pdf_show_logo', models.BooleanField(default=True, help_text='Show company logo on generated PDFs', verbose_name='Afficher le logo sur les PDF')),
                ('signature_certificate_path', models.CharField(blank=True, help_text='Path to digital signature certificate file (optional)', max_length=500, verbose_name='Chemin du certificat de signature')),
                ('signature_enabled', models.BooleanField(default=True, help_text='Enable digital signature feature for estimates', verbose_name='Signature électronique activée')),
                ('estimate_terms', models.TextField(blank=True, help_text='Default terms and conditions for estimates', verbose_name='Conditions générales des devis')),
                ('invoice_terms', models.TextField(blank=True, help_text='Default terms and conditions for invoices', verbose_name='Conditions générales des factures')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
