# Generated by Django 5.0.1 on 2025-10-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether the user has completed the initial onboarding flow', verbose_name='Onboarding terminé'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_step',
            field=models.IntegerField(default=1, help_text='Current step in onboarding process (1-4)', verbose_name="Étape d'onboarding"),
        ),
    ]
