# Generated by Django 5.0.1 on 2025-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_onboarding_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'Français')], default='en', help_text="User's preferred language for the interface", max_length=2, verbose_name='Langue préférée'),
        ),
    ]
