# Generated by Django 5.0.1 on 2025-10-31 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_preferred_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID for billing (denormalized for quick access)', max_length=255, verbose_name='Stripe Customer ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_tier',
            field=models.CharField(default='FREE', help_text='Current subscription tier (denormalized from Subscription model for quick access)', max_length=20, verbose_name='Subscription Tier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trial_ends_at',
            field=models.DateTimeField(blank=True, help_text='When trial period ends (denormalized for quick access)', null=True, verbose_name='Trial Ends At'),
        ),
    ]
