# Generated by Django 5.0.1 on 2025-11-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_vat_subject',
            field=models.BooleanField(default=True, help_text='Do you charge VAT (TVA) on your invoices? Micro-entrepreneurs below thresholds (€37,500 for services, €85,000 for goods) may be exempt under Article 293 B du CGI.', verbose_name='Assujetti à la TVA'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='default_tax_rate',
            field=models.DecimalField(choices=[(20.0, '20% - Taux normal (Standard rate)'), (10.0, '10% - Taux réduit (Restaurants, accommodation)'), (5.5, '5.5% - Taux réduit (Essential goods)'), (2.1, '2.1% - Taux super réduit (Newspapers, medicines)'), (0.0, '0% - Exonéré (Exempt/Not applicable)')], decimal_places=2, default=20.0, help_text='Default VAT/tax rate according to French law', max_digits=5, verbose_name='Taux de TVA par défaut (%)'),
        ),
    ]
