# Generated by Django 5.0.1 on 2025-11-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_userprofile_is_vat_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_type',
            field=models.CharField(blank=True, choices=[('MICRO_ENTREPRISE', 'Micro-entreprise / Auto-entrepreneur'), ('SASU', 'SASU (Société par Actions Simplifiée Unipersonnelle)'), ('SAS', 'SAS (Société par Actions Simplifiée)'), ('EURL', 'EURL (Entreprise Unipersonnelle à Responsabilité Limitée)'), ('SARL', 'SARL (Société à Responsabilité Limitée)'), ('EI', 'EI (Entreprise Individuelle)'), ('OTHER', 'Other')], help_text='Your legal business structure', max_length=50, verbose_name='Type de société'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_vat_subject',
            field=models.BooleanField(default=True, help_text='Do you charge VAT (TVA) on your invoices? All businesses with revenue below €37,500 (services) or €85,000 (goods) may be exempt under Article 293 B du CGI, regardless of legal status.', verbose_name='Assujetti à la TVA'),
        ),
    ]
