# Generated by Django 5.0.1 on 2025-11-02 16:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_company_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_tax_rate',
            field=models.DecimalField(choices=[(Decimal('20.00'), '20% - Taux normal (Standard rate)'), (Decimal('10.00'), '10% - Taux réduit (Restaurants, accommodation)'), (Decimal('5.50'), '5.5% - Taux réduit (Essential goods)'), (Decimal('2.10'), '2.1% - Taux super réduit (Newspapers, medicines)'), (Decimal('0.00'), '0% - Exonéré (Exempt/Not applicable)')], decimal_places=2, default=Decimal('20.00'), help_text='Default VAT/tax rate according to French law', max_digits=5, verbose_name='Taux de TVA par défaut (%)'),
        ),
    ]
