# Generated by Django 5.0.1 on 2025-10-20 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('company', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('proposal', 'Proposal Sent'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated deal value', max_digits=12, null=True)),
                ('probability', models.IntegerField(default=0, help_text='Win probability (0-100)')),
                ('source', models.CharField(choices=[('website', 'Website'), ('referral', 'Referral'), ('linkedin', 'LinkedIn'), ('cold_outreach', 'Cold Outreach'), ('event', 'Event'), ('other', 'Other')], default='other', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='leads_lead_user_id_8f1913_idx'), models.Index(fields=['expected_close_date'], name='leads_lead_expecte_6f96ea_idx')],
            },
        ),
    ]
